name: Test Runner

on:
  # trigger on any push to any branch
  push:
    branches:
      - '*'
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      
      - name: "Cache Go Modules"
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.19'

      - name: "Run Tests"
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
      
      - name: "Codecov: Upload Coverage"
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
